const records=[
{title:'2D Spatial Canvas',path:'../01-2d-spatial-canvas/index.html',keys:'2d p5 archive tree flower memory wind cotton letter',summary:'Three p5.js scenes translate family memory into a static archive, a mouse-driven wishing tree, and a cotton flower that blooms before letters descend.'},
{title:'3D Spatial Canvas',path:'../02-3d-spatial-canvas/index.html',keys:'3d three orbit ocean lantern routes constellation gravity',summary:'Three.js turns paper fragments into a cursor-shaped constellation, a moving sea of letters, and an orbiting archive lantern.'},
{title:'Temporal Structure',path:'../03-temporal-structure/index.html',keys:'temporal time d3 line chart annual water consumption population per capita nyc dep csv change',summary:'A D3 temporal study compares 46 years of NYC population, total water consumption, and per-capita demand through metric switching, tooltips, annual-change bars, and normalized lines.'},
{title:'Relational Structure',path:'../04-relational-structure/index.html',keys:'relational network platform labor algorithm boss nodes edges force d3',summary:'A D3 force network maps algorithmic management through 24 nodes, 48 relationships, filters, dragging, zooming, and relationship tracing.'},
{title:'Geospatial Structure',path:'../05-geospatial-structure/index.html',keys:'geospatial map mapbox restaurant columbia 800 broadway amsterdam geojson delivery',summary:'Mapbox combines NYC restaurant data, fallback GeoJSON, distance bands, cuisine filters, campus access points, and corridor proxies around Columbia.'},
{title:'Engagement Component',path:'../06-engagement-component/index.html',keys:'engagement poll firebase study space vote butler avery participation',summary:'A Firebase poll turns voluntary study-space choices into live aggregated counts and percentages while documenting participation limits.'},
{title:'Agent',path:'index.html',keys:'agent guide context chat retrieval assistant',summary:'This local context guide uses transparent keyword retrieval and links visitors to the most relevant object without exposing an API key.'}];
const messages=document.getElementById('messages'),form=document.getElementById('form'),input=document.getElementById('input');
document.querySelectorAll('.prompts button').forEach(b=>b.onclick=()=>{input.value=b.textContent;form.requestSubmit()});
form.onsubmit=e=>{e.preventDefault();const q=input.value.trim();if(!q)return;add('user',q);input.value='';setTimeout(()=>reply(answer(q)),160)};
function answer(q){const t=q.toLowerCase();if(/aesthetic|style|palette|color|design|typography/.test(t))return{body:'The design prioritizes quiet coherence, then legibility, object-first presentation, and restrained interaction. Warm ivory, mist, stone, soft sage, deep sage, charcoal, and a small muted-clay accent unify the seven objects. Instrument Serif is used for headings, while Inter is used for body text, captions, controls, and navigation.',path:'../../index.html#aesthetic',label:'Read the aesthetic priorities'};if(/dataset|data|csv|geojson|records/.test(t))return{body:'The project includes a 46-record NYC water-consumption CSV, 24-node and 48-edge network CSVs, NYC DOHMH restaurant records, local GeoJSON, and live aggregated Firebase poll counts.',path:'../03-temporal-structure/index.html',label:'Open Temporal Structure'};if(/begin|start|first|order/.test(t))return{body:'Begin with the 2D Spatial Canvas to learn the paper, flower, memory, and letter vocabulary. Then move through 3D, time, networks, maps, participation, and this guide.',path:'../01-2d-spatial-canvas/index.html',label:'Begin with 2D Spatial Canvas'};if(/d3/.test(t))return{body:'D3.js appears in Temporal Structure for interactive time-series, annual-change bars, and normalized comparison lines, and in Relational Structure for the force-directed network.',path:'../03-temporal-structure/index.html',label:'Open Temporal Structure'};let best=null,score=0;for(const r of records){let s=0;r.keys.split(' ').forEach(k=>{if(t.includes(k))s+=k.length>5?3:2});if(s>score){score=s;best=r}}if(!best)return{body:'Ask about p5.js, Three.js, D3, Mapbox, Firebase, platform labor, family memory, datasets, interactions, or the shared aesthetic.',path:'../../index.html#objects',label:'Browse all objects'};return{body:`<strong>${best.title}</strong>: ${best.summary}`,path:best.path,label:`Open ${best.title}`}}
function add(role,text){const a=document.createElement('article');a.className=role;a.innerHTML=`<small>${role==='user'?'YOU':'GUIDE'}</small><p></p>`;a.querySelector('p').textContent=text;messages.append(a);messages.scrollTop=messages.scrollHeight}function reply(r){const a=document.createElement('article');a.className='bot';a.innerHTML=`<small>GUIDE</small><p>${r.body}</p><p><a href="${r.path}">${r.label} →</a></p>`;messages.append(a);messages.scrollTop=messages.scrollHeight}